import { CardDesign, CardTheme, InstituteConfig, StudentProfile } from '../types/card';

export const DEFAULT_IMAGES = {
  malePortrait: '/src/assets/images/student_portrait_male_1790156283979.jpg',
  femalePortrait: '/src/assets/images/student_portrait_female_1790156297598.jpg',
  schoolLogo: '/src/assets/images/institute_emblem_seal_1790156310509.jpg',
};

export const CARD_THEMES: Record<string, CardTheme> = {
  'royal-navy': {
    id: 'royal-navy',
    nameGu: 'રોયલ નેવી અને ગોલ્ડ',
    nameEn: 'Royal Navy & Gold',
    primaryColor: '#0f2744',
    secondaryColor: '#1e3a8a',
    accentColor: '#d97706',
    textColor: '#ffffff',
    headerBg: 'from-blue-950 via-slate-900 to-blue-900',
    cardBg: '#ffffff',
    borderClass: 'border-blue-900/20',
  },
  'gseb-saffron': {
    id: 'gseb-saffron',
    nameGu: 'ગુજરાતી કેસરી અને મેરૂન',
    nameEn: 'GSEB Saffron & Maroon',
    primaryColor: '#991b1b',
    secondaryColor: '#c2410c',
    accentColor: '#f59e0b',
    textColor: '#ffffff',
    headerBg: 'from-amber-900 via-rose-950 to-red-900',
    cardBg: '#ffffff',
    borderClass: 'border-amber-700/20',
  },
  'emerald-gold': {
    id: 'emerald-gold',
    nameGu: 'એમરાલ્ડ ગ્રીન અને સોનેરી',
    nameEn: 'Emerald Green & Gold',
    primaryColor: '#064e3b',
    secondaryColor: '#047857',
    accentColor: '#eab308',
    textColor: '#ffffff',
    headerBg: 'from-emerald-950 via-teal-950 to-emerald-900',
    cardBg: '#ffffff',
    borderClass: 'border-emerald-900/20',
  },
  'crimson-ruby': {
    id: 'crimson-ruby',
    nameGu: 'રૂબી રેડ અને સિલ્વર',
    nameEn: 'Ruby Crimson & Slate',
    primaryColor: '#881337',
    secondaryColor: '#9f1239',
    accentColor: '#cbd5e1',
    textColor: '#ffffff',
    headerBg: 'from-rose-950 via-red-950 to-rose-900',
    cardBg: '#ffffff',
    borderClass: 'border-rose-900/20',
  },
  'slate-modern': {
    id: 'slate-modern',
    nameGu: 'મોર્ડન સ્લેટ અને કોબાલ્ટ',
    nameEn: 'Modern Slate & Indigo',
    primaryColor: '#1e293b',
    secondaryColor: '#334155',
    accentColor: '#6366f1',
    textColor: '#ffffff',
    headerBg: 'from-slate-950 via-slate-900 to-slate-800',
    cardBg: '#ffffff',
    borderClass: 'border-slate-800/20',
  },
  'cyber-teal': {
    id: 'cyber-teal',
    nameGu: 'સાયન્સ ટેક સ્યાન',
    nameEn: 'STEM Science Cyan',
    primaryColor: '#134e4a',
    secondaryColor: '#0f766e',
    accentColor: '#06b6d4',
    textColor: '#ffffff',
    headerBg: 'from-teal-950 via-cyan-950 to-teal-900',
    cardBg: '#ffffff',
    borderClass: 'border-teal-900/20',
  },
};

export const DEFAULT_INSTITUTE: InstituteConfig = {
  nameGu: 'શ્રી સરસ્વતી વિદ્યામંદિર હાઈસ્કૂલ',
  nameEn: 'Shree Saraswati Vidyamandir High School',
  affiliationGu: 'માન્યતા: ગુજ. માધ્યમિક અને ઉચ્ચતર માધ્યમિક શિક્ષણ બોર્ડ (GSEB)',
  affiliationEn: 'Affiliated to Gujarat Secondary & Higher Sec. Education Board',
  code: 'DISE CODE: 24070100123 / SSC CODE: 65.102',
  addressGu: 'સ્ટેશન રોડ, શારદા સર્કલ પાસે, રાજકોટ, ગુજરાત - ૩૬૦૦૦૧',
  addressEn: 'Station Road, Nr. Sharda Circle, Rajkot, Gujarat - 360001',
  phone: '+91 281 2456789 / 2456790',
  email: 'contact@saraswatividyamandir.edu.in',
  website: 'www.saraswatividyamandir.edu.in',
  logoUrl: DEFAULT_IMAGES.schoolLogo,
  principalSignatureUrl: '', // Generated via SVG canvas or preset
  principalStampUrl: '',
  principalTitleGu: 'આચાર્યશ્રી / અધિકૃત સહી',
  principalTitleEn: 'Principal / Authorized Sign',
};

export const SAMPLE_STUDENTS: StudentProfile[] = [
  {
    id: 'stud-1',
    fullNameGu: 'જયેન્દ્રસિંહ કે. ગોહિલ',
    fullNameEn: 'Jayendrasinh K. Gohil',
    studentId: 'SVM/2026/048',
    rollNo: '24',
    gradeGu: 'ધોરણ ૧૦ - અ (સામાન્ય પ્રવાહ)',
    gradeEn: 'Std 10th - Div A',
    academicYear: '2026 - 2027',
    dob: '15/08/2010',
    bloodGroup: 'O+',
    phone: '+91 98795 43210',
    emergencyContact: '+91 98250 12345',
    addressGu: 'પ્લોટ નં. ૨૪, સરદાર પટેલ સોસાયટી, કાલવાડ રોડ, રાજકોટ - ૩૬૦૦૦૫',
    addressEn: 'Plot No. 24, Sardar Patel Society, Kalawad Road, Rajkot - 360005',
    photoUrl: DEFAULT_IMAGES.malePortrait,
    gender: 'male',
    houseGu: 'ગીર હાઉસ (Gir House)',
    houseEn: 'Gir House (Green)',
    validUpto: '31/05/2027',
    extraFieldTitle: 'બસ રૂટ નં.',
    extraFieldValue: 'રૂટ-૦૭ (કાલાવડ રોડ)',
  },
  {
    id: 'stud-2',
    fullNameGu: 'દિયા એચ. શાહ',
    fullNameEn: 'Diya H. Shah',
    studentId: 'SVM/2026/112',
    rollNo: '09',
    gradeGu: 'ધોરણ ૧૨ - બ (વિજ્ઞાન પ્રવાહ)',
    gradeEn: 'Std 12th - Div B (Science)',
    academicYear: '2026 - 2027',
    dob: '22/11/2008',
    bloodGroup: 'B+',
    phone: '+91 94280 87654',
    emergencyContact: '+91 94280 87650',
    addressGu: 'બી-૩૦૨, શિવમ્ હાઇટ્સ, નાના મવા રોડ, રાજકોટ - ૩૬૦૦૦૪',
    addressEn: 'B-302, Shivam Heights, Nana Mava Road, Rajkot - 360004',
    photoUrl: DEFAULT_IMAGES.femalePortrait,
    gender: 'female',
    houseGu: 'સોમનાથ હાઉસ (Somnath)',
    houseEn: 'Somnath House (Blue)',
    validUpto: '31/05/2027',
    extraFieldTitle: 'બસ રૂટ નં.',
    extraFieldValue: 'રૂટ-૦૩ (નાના મવા)',
  },
  {
    id: 'stud-3',
    fullNameGu: 'આરવ એમ. પટેલ',
    fullNameEn: 'Aarav M. Patel',
    studentId: 'SVM/2026/015',
    rollNo: '03',
    gradeGu: 'ધોરણ ૯ - ક',
    gradeEn: 'Std 9th - Div C',
    academicYear: '2026 - 2027',
    dob: '04/03/2011',
    bloodGroup: 'A+',
    phone: '+91 97243 11223',
    emergencyContact: '+91 97243 11220',
    addressGu: '૧૫, વૈભવ બંગલોઝ, એરપોર્ટ રોડ, રાજકોટ - ૩૬૦૦૦૧',
    addressEn: '15, Vaibhav Bungalows, Airport Road, Rajkot - 360001',
    photoUrl: DEFAULT_IMAGES.malePortrait,
    gender: 'male',
    houseGu: 'સાપુતારા હાઉસ (Saputara)',
    houseEn: 'Saputara House (Red)',
    validUpto: '31/05/2027',
    extraFieldTitle: 'બસ રૂટ નં.',
    extraFieldValue: 'સ્વયં વાહન (Self Transport)',
  },
];

export const DEFAULT_DESIGN: CardDesign = {
  layout: 'vertical',
  themeId: 'royal-navy',
  language: 'gu',
  showBarcode: true,
  showQrCode: true,
  showChip: false,
  showHologram: true,
  showLanyardSlot: true,
  showLanyardStrap: true,
  showWatermark: true,
  cardCurvature: 'rounded-xl',
  photoShape: 'rounded',
};
